### ISSUE TITLE
Authorization Header set on WebTarget interface ignored

### ISSUE THREAD

**Issue by hgaglani** [pingidentity/scim2#106]
To start with, Thank you for all the hard work. This library is pretty amazing and very easy to use for SCIM client implementation. 

Bug Details:
I'd like to set the Authorization headers on the WebTarget object passed during ScimService creation like this:
Client client = ClientBuilder.newClient();
WebTarget target = client.target(url);
target.request().header("Authorization", "Basic test123")
ScimService service = new ScimService(target);
service.create("/Users", scimResource);

However, the auth header doesn't make it all the way to the headers set in CreateRequestBuilder class.  Only way I was able to bypass this was do this:
CreateRequestBuilder requestBuilder = scimService.createRequest("Users", scimResource);
requestBuilder.header("Authorization", "Basic  test123"));
requestBuilder.invoke();

Because of this, I am unable to use the helper classes on ScimService and having to mock requestBuilder stuff in my tests that are absolutely unnecessary and is an implementation detail that I don't need to worry about. Let me know if you need any other information.

**Comment by lachee10** [comment]
How about registering your auth information with the client you are creating? Doesn't work this for you?

Something like this should work:

```
import org.glassfish.jersey.client.authentication.HttpAuthenticationFeature;

Client client = ClientBuilder.newClient();
HttpAuthenticationFeature feature = HttpAuthenticationFeature.basic(userName,
            password);
client.register(feature);
WebTarget target = client.target(url);
....
```

**Comment by hgaglani** [comment]
Nope doesn't matter. When i step through the code: 

After this point the client reference is not used.
return new CreateRequestBuilder<T>(baseTarget.path(endpoint), resource); 

Your RequestBuilder.java class, buildRequest method uses headers that are set only on the requestBuilder and not on the target. This is where the bug is.

**Comment by braveulysses** [comment]
@hgaglani, it's definitely possible to configure basic authn in the manner suggested by @lachee10, with one small change: The `HttpAuthenticationFeature` should be registered with a `ClientConfig`, which is then used to create the `Client`.

I've added a page to the wiki that demonstrates some typical JAX-RS Client configuration cases: https://github.com/pingidentity/scim2/wiki/JAX-RS-Client-examples
