### ISSUE TITLE
duplicate class "com.unboundid.scim2.common.utils.Version" betwen scim2-sdk-client and scim2-sdk-common

### ISSUE THREAD

**Issue by hauntingEcho** [pingidentity/scim2#109]
When attempting to build a fat jar which uses the scim2-sdk-client library, maven gives the following warning:
```
[WARNING] scim2-sdk-client-2.1.3.jar, scim2-sdk-common-2.1.3.jar define 1 overlapping classes:
[WARNING]   - com.unboundid.scim2.common.utils.Version
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
```
When classes have naming conflicts, it is undefined which is loaded.  While it looks like the file is identical between them, this leaves an opening for issues if they do diverge.

Since scim2-sdk-client imports scim2-sdk-common, the class can just be deleted from scim2-sdk-client.

**Comment by s1tsao** [comment]
This issue still appears for me on version 2.2.1

**Comment by hauntingEcho** [comment]
this is really a duplicate of #91 - closing this ticket
