### ISSUE TITLE
Migrate TestNG to JUnit 5

### ISSUE THREAD

**Issue by Krzysztof1985** [pingidentity/scim2#163]
Hello, 

I am using SCIM2 library and some parts of the application seems to be old. 
I rewrote some tests in SDK-common module to use Junit5 + fix some tests (no assertions at all).

In JUnit 5 approach tests looks more cleaner.

Regards
Krzysztof

**Comment by kqarryzada** [comment]
Hi Krzysztof. I see your PR in #164. Unfortunately, Ping Identity does not accept third-party code contributions, and we don't have plans to move to the SCIM SDK's test framework to JUnit at this time. I appreciate your interest, though.
