### ISSUE TITLE
Make the SCIM compatible Jackson JSON mapper understand SCIM POJOs better 

### ISSUE THREAD

**Issue by digitalperk** [pingidentity/scim2#19]
POJOs currently have to extend BaseScimResource to get the behavior of expecting the SCIM common attributes (schemas, id, externalId, and meta). We should make the SCIM compatible Jackson JSON mapper always ignore these if the POJO didn't define them. 

BaseScimResource currently ignores unknown attributes. This should also be changed to throw an error if the attribute is unknown.

**Comment by kqarryzada** [comment]
Closing this issue since we have not been able to prioritize this work.
