### ISSUE TITLE
Incorrect parsing of scim filter

### ISSUE THREAD

**Issue by agustin-avila** [pingidentity/scim2#79]
The filter:
`displayName sw \"e\" and displayName sw \"f\" and displayName sw \"g\" or nickName sw \"a\"`
parsed with `Filter.fromString(filter)` results in 
![image](https://user-images.githubusercontent.com/910262/28404914-82bae9a0-6d6e-11e7-903f-2fe5dde30d9f.png)

The offending part is in yellow, that shouldn't be there.

The expected behaviour would be the one of parsing (note the brackets):
`(displayName sw \"e\" and displayName sw \"f\" and displayName sw \"g\") or nickName sw \"a\"`
![image](https://user-images.githubusercontent.com/910262/28404807-1c7bfc88-6d6e-11e7-8923-16022d5d765e.png)

**Comment by digitalperk** [comment]
I'm not sure I understand your concern. The parsed filter expression tree is different because the filter strings are very different. The filter parser does not try support optimizing the filter by removing redundant components.
