### ISSUE TITLE
javax.ws.rs.ProcessingException: java.net.ProtocolException: Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by asaf** [pingidentity/scim2#83]
Seems like java.net.HttpURLConnection does not support the PATCH http method (yet, although it's in the [standard](standard (http://tools.ietf.org/html/rfc5789) for 7 years now, causing an exception during `modifyRequest` invocation such:

```java
scimService.modifyRequest("Users", user.getId())
           .replaceValue("password", "new-password")
           .invoke(GenericScimResource.class);
```

Do we have any workaround for that?

Thanks.

**Comment by digitalperk** [comment]
If you are using Jersey, you can use another client transport connector:
https://jersey.github.io/documentation/latest/client.html#d0e4971
We suggest using the Apache HTTP Client connector.
