### ISSUE TITLE
update SchemaChecker Javadoc to clarify usage

### ISSUE THREAD

**Issue by s-kramer** [pingidentity/scim2#93]
SchemaChecker implementation does not conform to SCIM2.0 standard with regards to ignoring\asserting fields with mutability type READ_ONLY or IMMUTABLE

[SCIM Protocol Specification  3.5.1.  Replacing with PUT](https://tools.ietf.org/html/rfc7644#section-3.5.1)
> immutable  If one or more values are already set for the attribute,
      the input value(s) MUST match, or HTTP status code 400 SHOULD be
      returned with a "scimType" error code of "mutability".  If the
      service provider has no existing values, the new value(s) SHALL be
      applied.
   readOnly  Any values provided SHALL be ignored.

[SCIM Protocol Specification 3.3.  Creating Resources](https://tools.ietf.org/html/rfc7644#section-3.3)

>   In the request body, attributes whose mutability is "readOnly"
      (see Sections 2.2 and 7 of [RFC7643]) SHALL be ignored.

Expected behavior: 
ReadOnly fields specified in request's body are ignored, as stated in the specification.
Values of immutable fields in the request are checked against the actual values.

Actual behavior:
The SchemaChecker fails with BadRequestException
```
com.unboundid.scim2.common.exceptions.BadRequestException: Attribute id is read-only, Attribute meta is read-only, Attribute meta.created is read-only, Attribute meta.location is read-only, Attribute meta.resourceType is read-only
        at com.unboundid.scim2.common.exceptions.BadRequestException.mutability(BadRequestException.java:173)
```

Steps to reproduce:
1. Issue a GET request
2. Copy the response body
3. Send it again in a PUT request

This is causing a lot of problems as the workaround requires removing the offending fields before the validation and performing the checks by hand.

@braveulysses @digitalperk Can anything be done with this issue?

**Comment by s-kramer** [comment]
As a workaround `SchemaChecker`'s `removeReadOnlyAttributes` can be used before processing

**Comment by kennethleo** [comment]
@braveulysses suggests that we could address this with Javadoc updates:

> The correct way to use the checkCreate(...) and checkModify(...) methods is to call removeReadOnlyAttributes(...) first. The Javadocs for the first two methods don't mention this, though, so you'd only know if you had also read the Javadocs for removeReadOnlyAttributes(...).
